// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: e2Wrjg6Dz94BkfogsCYoEo
// Component: UV4kMT6l6aof

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: e2Wrjg6Dz94BkfogsCYoEo/projectcss
import sty from "./PlasmicBlogCardLeftSmall.module.css"; // plasmic-import: UV4kMT6l6aof/css

createPlasmicElementProxy;

export type PlasmicBlogCardLeftSmall__VariantMembers = {};
export type PlasmicBlogCardLeftSmall__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlogCardLeftSmall__VariantsArgs;
export const PlasmicBlogCardLeftSmall__VariantProps =
  new Array<VariantPropType>();

export type PlasmicBlogCardLeftSmall__ArgsType = {
  children?: React.ReactNode;
  title?: React.ReactNode;
  title2?: React.ReactNode;
  children2?: React.ReactNode;
  title3?: React.ReactNode;
};
type ArgPropType = keyof PlasmicBlogCardLeftSmall__ArgsType;
export const PlasmicBlogCardLeftSmall__ArgProps = new Array<ArgPropType>(
  "children",
  "title",
  "title2",
  "children2",
  "title3"
);

export type PlasmicBlogCardLeftSmall__OverridesType = {
  root?: Flex__<"div">;
  h6?: Flex__<"h6">;
  header?: Flex__<"div">;
  span?: Flex__<"span">;
  body?: Flex__<"div">;
  header2?: Flex__<"div">;
  body2?: Flex__<"div">;
};

export interface DefaultBlogCardLeftSmallProps {
  children?: React.ReactNode;
  title?: React.ReactNode;
  title2?: React.ReactNode;
  children2?: React.ReactNode;
  title3?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBlogCardLeftSmall__RenderFunc(props: {
  variants: PlasmicBlogCardLeftSmall__VariantsArgs;
  args: PlasmicBlogCardLeftSmall__ArgsType;
  overrides: PlasmicBlogCardLeftSmall__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <PlasmicImg__
        alt={""}
        className={classNames(sty.img___01Qp)}
        displayHeight={"118px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"auto"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"134px"}
        height={"200"}
        loading={"lazy"}
        src={(() => {
          try {
            return $ctx.plasmicCmsPostsItem.data.thumbnail.url;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <div className={classNames(projectcss.all, sty.freeBox__isfQq)}>
        <h6
          data-plasmic-name={"h6"}
          data-plasmic-override={overrides.h6}
          className={classNames(
            projectcss.all,
            projectcss.h6,
            projectcss.__wab_text,
            sty.h6
          )}
        >
          {"Enter some text"}
        </h6>
        <div
          data-plasmic-name={"header"}
          data-plasmic-override={overrides.header}
          className={classNames(projectcss.all, sty.header)}
        >
          <span
            data-plasmic-name={"span"}
            data-plasmic-override={overrides.span}
            className={classNames(
              projectcss.all,
              projectcss.span,
              projectcss.__wab_text,
              sty.span
            )}
          >
            {"Enter some text"}
          </span>
          {renderPlasmicSlot({
            defaultContents: "Sample card  title this is it",
            value: args.title,
            className: classNames(sty.slotTargetTitle)
          })}
          {false
            ? renderPlasmicSlot({
                defaultContents: "Card title",
                value: args.title3,
                className: classNames(sty.slotTargetTitle3)
              })
            : null}
        </div>
        <div
          data-plasmic-name={"body"}
          data-plasmic-override={overrides.body}
          className={classNames(projectcss.all, sty.body)}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <React.Fragment>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xl98Y
                  )}
                >
                  {"Enter some text"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uo4R
                  )}
                >
                  {"something here"}
                </div>
              </React.Fragment>
            ),
            value: args.children
          })}
        </div>
      </div>
      {false ? (
        <div className={classNames(projectcss.all, sty.freeBox__maM3B)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__haOlo)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"283px"}
            height={"200"}
            loading={"lazy"}
            src={(() => {
              try {
                return $ctx.plasmicCmsPostsItem.data.thumbnail.url;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />

          <div
            data-plasmic-name={"header2"}
            data-plasmic-override={overrides.header2}
            className={classNames(projectcss.all, sty.header2)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__lq2Sj)}>
              {renderPlasmicSlot({
                defaultContents: "Card title",
                value: args.title2,
                className: classNames(sty.slotTargetTitle2)
              })}
            </div>
          </div>
          <div
            data-plasmic-name={"body2"}
            data-plasmic-override={overrides.body2}
            className={classNames(projectcss.all, sty.body2)}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yve8I
                    )}
                  >
                    {"Enter some text"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__omrg4
                    )}
                  >
                    {"something here"}
                  </div>
                </React.Fragment>
              ),
              value: args.children2
            })}
          </div>
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h6", "header", "span", "body", "header2", "body2"],
  h6: ["h6"],
  header: ["header", "span"],
  span: ["span"],
  body: ["body"],
  header2: ["header2"],
  body2: ["body2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h6: "h6";
  header: "div";
  span: "span";
  body: "div";
  header2: "div";
  body2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlogCardLeftSmall__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlogCardLeftSmall__VariantsArgs;
    args?: PlasmicBlogCardLeftSmall__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlogCardLeftSmall__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlogCardLeftSmall__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBlogCardLeftSmall__ArgProps,
          internalVariantPropNames: PlasmicBlogCardLeftSmall__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBlogCardLeftSmall__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogCardLeftSmall";
  } else {
    func.displayName = `PlasmicBlogCardLeftSmall.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogCardLeftSmall = Object.assign(
  // Top-level PlasmicBlogCardLeftSmall renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h6: makeNodeComponent("h6"),
    header: makeNodeComponent("header"),
    span: makeNodeComponent("span"),
    body: makeNodeComponent("body"),
    header2: makeNodeComponent("header2"),
    body2: makeNodeComponent("body2"),

    // Metadata about props expected for PlasmicBlogCardLeftSmall
    internalVariantProps: PlasmicBlogCardLeftSmall__VariantProps,
    internalArgProps: PlasmicBlogCardLeftSmall__ArgProps
  }
);

export default PlasmicBlogCardLeftSmall;
/* prettier-ignore-end */
